name: Master deployment

on:
  push:
    branches:
      - master
  schedule:
    # run at 23:00 UTC+0 daily
    - cron: '0 23 * * *'

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Netlify deployment
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
        run: |
          yarn
          yarn build
          npx netlify-cli deploy --dir=out_publish --functions=out_functions --prod --message='Deployment for ${GITHUB_REF}'
